variables:
  baseimg: "docker-registry.pdbld.f5net.com/${CI_PROJECT_NAMESPACE}/marathon-bigip-ctlr"

stages:
  - test
  - build
  - deploy

unit_test:
  script:
    - pip install -r marathon-build-requirements.txt
    - pip install -r marathon-runtime-requirements.txt
    - flake8 --exclude=docs/ ./
    - ./build-tools/lint.sh
    - coverage run -m unittest discover -v
    - coverage html
    - coverage report
  tags:
    - docker
  artifacts:
    untracked: true
    paths:
      - htmlcov/*
  stage: test

build docs:
  image: docker-registry.pdbld.f5net.com/tools/containthedocs:master
  script:
    - cp ATTRIBUTIONS.md docs/_static
    - ./build-tools/test-docs.sh
  tags:
    - docker
  stage: build
  artifacts:
    paths:
      - docs/_build/html
  dependencies:
    - attributions generator


# Create the docker container and upload it to the internal docker registry with the tags
#   <PROJ_NAMESPACE>/marathon-bigip-ctlr:<BRANCH>
#   <PROJ_NAMESPACE>/marathon-bigip-ctlr:<BRANCH>-<BUILD_ID>
#   <PROJ_NAMESPACE>/marathon-bigip-ctlr:<BRANCH>-<PIPELINE_ID>
dockerize:
  script:
    - export IMG_TAG="${baseimg}:${CI_BUILD_REF}"
    - ./build-tools/build-runtime-images.sh
    - docker tag "$IMG_TAG" "$baseimg:$CI_BUILD_REF_NAME"
    - docker tag "$IMG_TAG" "$baseimg:$CI_BUILD_REF_NAME-$CI_BUILD_ID"
    - docker tag "$IMG_TAG" "$baseimg:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID"
    - docker push "$IMG_TAG"
    - docker push "$baseimg:$CI_BUILD_REF_NAME"
    - docker push "$baseimg:$CI_BUILD_REF_NAME-$CI_BUILD_ID"
    - docker push "$baseimg:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID"
  stage: deploy
  tags:
    - docker-build


attributions generator:
  image: docker-registry.pdbld.f5net.com/velcro/attributions-generator:master
  stage: test
  script:
    - /usr/local/bin/run-backends.sh $PWD
    - node /frontEnd/frontEnd.js $PWD
  tags:
    - docker
  artifacts:
    paths:
      - Licenses_generated.json
      - flatfile_attributions.json
      - golang_attributions.json
      - pip_attributions.json
      - ATTRIBUTIONS.md

Publish docs to internet:
  # Publish ONLY 1.0-stable to the internet.
  image: docker-registry.pdbld.f5net.com/tools/containthedocs:master
  stage: deploy
  tags:
   - docker
  only:
   - 1.0-stable@velcro/marathon-bigip-controller
  dependencies:
    - build docs
  script:
    - publish-product-docs-to-prod connectors/marathon-bigip-ctlr v1.0
